### ISSUE TITLE
Hi! Derek Dang

### ISSUE THREAD

**Issue by sadazs** [dqdang/digested-clips#3]
Do you can make pack requeri and guide how to install and use
many thank!

**Comment by dqdang** [comment]
Sorry, this isn't maintained anymore. I'll probably try to rewrite most of this on my own later in the future. If you want to fork the repository and make your own, feel free to do so.

**Comment by dqdang** [comment]
I wrote some documentation. Take a look and see if it helps. Don't plan to make it into an out of the box application.
