### ISSUE TITLE
Error 400: redirect_uri_mismatch

### ISSUE THREAD

**Issue by KauzDs** [dqdang/digested-clips#5]
```
Authorization Error
Error 400: redirect_uri_mismatch
The redirect URI in the request, http://localhost:8080/, does not match the ones authorized for the OAuth client. To update the authorized redirect URIs, visit:.
```

It seems I should've changed the "redirect_uris" line in the `client_secrets.json` but I don't know what to change it to?

**Comment by dqdang** [comment]
You probably don't need to change the redirect_uris in the ``client_secrets.json`` line. The only time I've seen this is during Twitch's authorization flow. For this line:
``https://id.twitch.tv/oauth2/authorize?client_id=CID&redirect_uri=http://localhost&scope=clips:edit&response_type=code``,
Check your application in Twitch; see if the redirect_uri is the same as what you have when getting the authorization code.

**Comment by dqdang** [comment]
For Google's redirect_uris, I left the fields empty at the bottom:
![image](https://user-images.githubusercontent.com/10083357/86491325-5d967a00-bd1f-11ea-8f6a-97d084519c4b.png)

This is my clients_secrets.json:
![image](https://user-images.githubusercontent.com/10083357/86491383-959dbd00-bd1f-11ea-861c-d14a17b4b343.png)
